[project]
name = "budget-planner"
description = "A comprehensive budget planning and analytics system for Stacks blockchain"
authors = ["Hammed <hamsohood@gmail.com>"]
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[contracts.budget-planner]
path = "contracts/budget-planner.clar"
depends_on = []

[contracts.budget-analytics]
path = "contracts/budget-analytics.clar"
depends_on = ["budget-planner"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
